<a href="https://colab.research.google.com/github/nithingovindugari/IntrotoQuantum_Project/blob/main/Project_Phase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# Deutsch Algorithm Simulator


import numpy as np, math

#For Not gate
def Xgate(a,b):
    matrix = np.array([[float(a)],[float(b)]])
    X = np.array([[0,1],[1,0]])
    # result = X.dot(matrix)
    result = np.matmul(X,matrix)
    for i in range(0, len(matrix)):
        print('{} {} '.format(X[i],matrix[i]))
    print('\n')       
    print(result)
 
# Calling Not Gate 
print("Enter  two values for 1 qubit Not gate")
y = Xgate(int(input("Enter the 1 st value  --   ")),\
            int(input('Enter the 2nd value   --   ')))

Enter  two values for 1 qubit Not gate
Enter the 1 st value  --   1
Enter the 2nd value   --   0
[0 1] [1.] 
[1 0] [0.] 


[[0.]
 [1.]]


In [ ]:
#XOR or CNOT Gate
import numpy as np, math
def XORgate(a,b,c,d):
    matrix = np.array([[float(a)],[float(b)],[float(c)],[float(d)]])
    XOR = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
    result = np.matmul(XOR,matrix)
    for i in range(0, len(matrix)):
          print(('{} {} '.format(XOR[i],matrix[i])))
    print('\n')
    print(result)

print("Enter  two values for 2 qubit CNot/XOR gate and it will be in the form of [a,b,c,d]")
y = XORgate((int(input('Enter the 1 st value   --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (int(input('Enter the 3rd value    --   '))),\
            (int(input('Enter the 4th  value   --   '))))


Enter  two values for 2 qubit CNot/XOR gate and it will be in the form of [a,b,c,d]
Enter the 1 st value   --   1
Enter the 2nd value    --   0
Enter the 3rd value    --   1
Enter the 4th  value   --   0
[1 0 0 0] [1.] 
[0 1 0 0] [0.] 
[0 0 0 1] [1.] 
[0 0 1 0] [0.] 


[[1.]
 [0.]
 [0.]
 [1.]]


In [ ]:
#Swap Gate

import numpy as np, math
def SWAPgate(a,b,c,d):
    matrix = np.array([[float(a)],[float(b)],[float(c)],[float(d)]])
    SWAP = np.array([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]])
    result = np.matmul(SWAP,matrix)    
    for i in range(0, len(matrix)):
          print('{} {} '.format(SWAP[i],matrix[i]))
    print('\n')
    print(result)

#Calling SWAP gate  
print("Enter  two values for 2 qubit SWAP gate and it will be in the form of [a,b,c,d]")
y = SWAPgate((int(input('Enter the 1 st value   --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (int(input('Enter the 3rd value    --   '))),\
            (int(input('Enter the 4 th value   --   '))))

Enter  two values for 2 qubit SWAP gate and it will be in the form of [a,b,c,d]
Enter the 1 st value   --   1
Enter the 2nd value    --   1
Enter the 3rd value    --   0
Enter the 4 th value   --   1
[1 0 0 0] [1.] 
[0 0 1 0] [1.] 
[0 1 0 0] [0.] 
[0 0 0 1] [1.] 


[[1.]
 [0.]
 [1.]
 [1.]]


In [ ]:
#one qubit phase shift gate
import numpy as np, math
def onebit_PS(a,b,phi):
    matrix = np.array([[float(a)],[float(b)]])
    onebit_PS = np.array([[1,0],[0,np.around(np.cos(phi), decimals=5)+1j*np.around(np.sin(phi), decimals=5)]])
    result = np.matmul(onebit_PS,matrix)    
    for i in range(0, len(matrix)):
          print('{} {} '.format(onebit_PS[i],matrix[i]))
    print('\n')
    print(result)
  

#Calling onebit phase shift gate  
print("Enter  two values for 1 qubit phase shift gate and it will be in the form of [a,b,phase value]")
y = onebit_PS((int(input('Enter the 1 st value   --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (float(input('Enter the phase value  --   '))))


Enter  two values for 1 qubit phase shift gate and it will be in the form of [a,b,phase value]
Enter the 1 st value   --   0
Enter the 2nd value    --   1
Enter the phase value  --   3.14
[1.+0.j 0.+0.j] [0.] 
[ 0.+0.j      -1.+0.00159j] [1.] 


[[ 0.+0.j     ]
 [-1.+0.00159j]]


In [ ]:
#Two qubit phase shift gate
import numpy as np, math
def twobit_PS(a,b,c,d,phi):
    matrix = np.array([[float(a)],[float(b)],[float(c)],[float(d)]])
    twobit_PS = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,np.around(np.cos(phi), decimals=5)+1j*np.around(np.sin(phi), decimals=5)]]) 
    result = np.matmul(twobit_PS,matrix)
    for i in range(0, len(matrix)):
        print('{} {} '.format(twobit_PS[i],matrix[i]))
    print('\n')
    print(result)

print("Enter  two values for two qubit phase shift gate and it will be in the form of [a,b,c,d, phase value]")
y = twobit_PS((int(input('Enter the 1st value    --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (int(input('Enter the 3rd   value  --   '))),\
            (int(input('Enter the 4th value    --   '))),\
            (float(input('Enter the phase value  --   '))))

Enter  two values for two qubit phase shift gate and it will be in the form of [a,b,c,d, phase value]
Enter the 1st value    --   1
Enter the 2nd value    --   0
Enter the 3rd   value  --   1
Enter the 4th value    --   1
Enter the phase value  --   3.14
[1.+0.j 0.+0.j 0.+0.j 0.+0.j] [1.] 
[0.+0.j 1.+0.j 0.+0.j 0.+0.j] [0.] 
[0.+0.j 0.+0.j 1.+0.j 0.+0.j] [1.] 
[ 0.+0.j       0.+0.j       0.+0.j      -1.+0.00159j] [1.] 


[[ 1.+0.j     ]
 [ 0.+0.j     ]
 [ 1.+0.j     ]
 [-1.+0.00159j]]


In [ ]:
import numpy as np, math
def toffoli(a,b,c,d,e,f,g,h):
      matrix = np.array([[float(a)],[float(b)],[float(c)],[float(d)],[float(e)],[float(f)],[float(g)],[float(h)]]) 
      toffoli = np.array([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0]])
      result = np.matmul(toffoli,matrix)  
      for i in range(0, len(matrix)):
            print('{} {} '.format(toffoli[i],matrix[i]))
      print('\n')
      print(result)
print("Enter  two values for 3 bit ccnot or toffoli gate and it will be in the form of [a,b,c,d,e,f,g,h]")
y = toffoli((int(input('Enter the 1 st value   --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (int(input('Enter the 3rd value    --   '))),\
            (int(input('Enter the 4th value    --   '))),\
            (int(input('Enter the 5th value    --   '))),\
            (int(input('Enter the 6th value    --   '))),\
            (int(input('Enter the 7th value    --   '))),\
            (int(input('Enter the 8th value    --   '))))

Enter  two values for 3 bit ccnot or toffoli gate and it will be in the form of [a,b,c,d,e,f,g,h]
Enter the 1 st value   --   0
Enter the 2nd value    --   0
Enter the 3rd value    --   0
Enter the 4th value    --   0
Enter the 5th value    --   0
Enter the 6th value    --   0
Enter the 7th value    --   1
Enter the 8th value    --   0
[1 0 0 0 0 0 0 0] [0.] 
[0 1 0 0 0 0 0 0] [0.] 
[0 0 1 0 0 0 0 0] [0.] 
[0 0 0 1 0 0 0 0] [0.] 
[0 0 0 0 1 0 0 0] [0.] 
[0 0 0 0 0 1 0 0] [0.] 
[0 0 0 0 0 0 0 1] [1.] 
[0 0 0 0 0 0 1 0] [0.] 


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]


In [ ]:
import numpy as np, math
def five_Hgate(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,bb,cc,dd,ee,ff):
      H = 1/math.sqrt(2)*np.array([[1,1],[1,-1]])
      matrix = np.array([[a],[b],[c],[d],[e],[f],[g],[h],[i],[j],[k],[l],[m], \
                         [n],[o],[p],[q],[r],[s],[t],[u],[v],[w],[x],[y],[z], \
                        [aa],[bb],[cc],[dd],[ee],[ff]]) 
      print(matrix)
      five_Hgate = np.kron(H,np.kron(H,np.kron(H,np.kron(H,H))))
      result = np.matmul(five_Hgate,matrix)
      print('\n','\n'"Find below output where five qubit Hadamard applied to above statp")
      print('\n',result)
print("Here standard base input is given as it is very big to take input below and it\
 is dynamic and we can change value any time" )

print("It will be in the form of Hadamard gate applied to basis state ")    


five_Hgate(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)




In [ ]:
# Phase 2 Code

In [ ]:
# AS i have made all the gates runtime and to keep the individuality seperate am re declaring the gates

In [ ]:
import numpy as np, math

#Not gate matrix
X = np.array([[0,1],[1,0]])               

#CNOT or XOR gate matrix
XOR = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]) 

#Identity gate matrix
I = np.array([[1,0],[0,1]])

#Hadamard gate matrix
H = 1/math.sqrt(2)*np.array([[1,1],[1,-1]])   #Hadamard gate

#Zero_state
base_state = np.array([[1],[0],[0],[0]])

#Hadamard gate
two_Hgate = np.kron(H,H)                      #Two bit Hadamard gate

# As Not gate is 1 qubit gate we need to make it 2 qubit by tensor product wit I

#When Identity is in MSB and Not gate is in LSB  ( I ⊗ X)
I_tens_X =  np.kron(I,X)

#When Not gat is in MSB and Identity is in LSB  ( X ⊗ I )
X_tens_I =  np.kron(X,I)

#When Hadamard gate is in MSB and Identity is in LSB  ( H ⊗ I )

H_tens_I = np.kron(H,I)


# We know we have four oracles ( Two constant and Two balanced)

# i)   Constant where it always gives zero irrespective of input
Oracle1 = np.kron(I,I)  # our oracle circuit for this will be simply an identity

# ii)  Constant where it always gives one irrespective of input
Oracle2 = I_tens_X  # we flips LSB irrespective of input. A quantum circuit will simply apply a NOT to the LSB

#iii)  Balanced where it gives zero as output when input is zero and one when input is one
Oracle3 = XOR  # our oracle circuit for this will be control gate 
               # If MSB is one then it switches the target bit

# iv) Balanced where it gives zero as output when input is one and zero when input is one
Oracle4 = XOR.dot(I_tens_X)  # our oracle circuit for this will be control gate and Not gate
               # If MSB is one then it switches the target bit back to basic state

# print(Oracle4)    


In [ ]:
def Deutsch(Oracle_type):
  # Initial step is common for all the functions
  step1 = two_Hgate.dot(I_tens_X.dot(base_state))
  count = 0
  MSB_0 = []
  MSB_1 = []
  print('─' * 25)
  print("Oracle")
  print(Oracle_type)
  for i in range(0,100):
    result = H_tens_I.dot(Oracle_type.dot(step1))
    if i == 99:
      print("Result")
      print(result)
    if result[2] == 0 and result[3] == 0:
      MSB_0.append(1)
    else:
      MSB_1.append(1)
  print("MSB = 0 : {} iterations".format(len(MSB_0)))
  print("MSB = 1 : {} iterations".format(len(MSB_1)))
  print('─' * 25)




In [ ]:
Deutsch(Oracle1)
print("MSB is always zero state for constant functions")
Deutsch(Oracle2)
print("MSB is always zero state for constant functions")
Deutsch(Oracle3)
print("MSB is always one state for balanced functions")
Deutsch(Oracle4)
print("MSB is always one state for balanced functions")

─────────────────────────
Oracle
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Result
[[ 0.70710678]
 [-0.70710678]
 [ 0.        ]
 [ 0.        ]]
MSB = 0 : 100 iterations
MSB = 1 : 0 iterations
─────────────────────────
MSB is always zero state for constant functions
─────────────────────────
Oracle
[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]
Result
[[-0.70710678]
 [ 0.70710678]
 [ 0.        ]
 [ 0.        ]]
MSB = 0 : 100 iterations
MSB = 1 : 0 iterations
─────────────────────────
MSB is always zero state for constant functions
─────────────────────────
Oracle
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
Result
[[ 0.        ]
 [ 0.        ]
 [ 0.70710678]
 [-0.70710678]]
MSB = 0 : 0 iterations
MSB = 1 : 100 iterations
─────────────────────────
MSB is always one state for balanced functions
─────────────────────────
Oracle
[[0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Result
[[ 0.        ]
 [ 0.        ]
 [-0.70710678]
 [ 0.70710678]]
MSB = 0 : 0 iterations
MSB = 1 : 100 iterations
───