<a href="https://colab.research.google.com/github/nithingovindugari/IntrotoQuantum_Project/blob/main/Project_Code_phase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np, math

#For Not gate
def Xgate(a,b):
    matrix = np.array([[float(a)],[float(b)]])
    X = np.array([[0,1],[1,0]])
    # result = X.dot(matrix)
    result = np.matmul(X,matrix)
    for i in range(0, len(matrix)):
        print('{} {} '.format(X[i],matrix[i]))
    print('\n')       
    print(result)
 
# Calling Not Gate 
print("Enter  two values for 1 qubit Not gate")
y = Xgate(int(input("Enter the 1 st value  --   ")),\
            int(input('Enter the 2nd value   --   ')))

Enter  two values for 1 qubit Not gate
Enter the 1 st value  --   1
Enter the 2nd value   --   0
[0 1] [1.] 
[1 0] [0.] 


[[0.]
 [1.]]


In [ ]:
#XOR or CNOT Gate
import numpy as np, math
def XORgate(a,b,c,d):
    matrix = np.array([[float(a)],[float(b)],[float(c)],[float(d)]])
    XOR = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
    result = np.matmul(XOR,matrix)
    for i in range(0, len(matrix)):
          print(('{} {} '.format(XOR[i],matrix[i])))
    print('\n')
    print(result)

print("Enter  two values for 2 qubit CNot/XOR gate and it will be in the form of [a,b,c,d]")
y = XORgate((int(input('Enter the 1 st value   --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (int(input('Enter the 3rd value    --   '))),\
            (int(input('Enter the 4th  value   --   '))))


Enter  two values for 2 qubit CNot/XOR gate and it will be in the form of [a,b,c,d]
Enter the 1 st value   --   1
Enter the 2nd value    --   0
Enter the 3rd value    --   1
Enter the 4th  value   --   0
[1 0 0 0] [1.] 
[0 1 0 0] [0.] 
[0 0 0 1] [1.] 
[0 0 1 0] [0.] 


[[1.]
 [0.]
 [0.]
 [1.]]


In [ ]:
#Swap Gate

import numpy as np, math
def SWAPgate(a,b,c,d):
    matrix = np.array([[float(a)],[float(b)],[float(c)],[float(d)]])
    SWAP = np.array([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]])
    result = np.matmul(SWAP,matrix)    
    for i in range(0, len(matrix)):
          print('{} {} '.format(SWAP[i],matrix[i]))
    print('\n')
    print(result)

#Calling SWAP gate  
print("Enter  two values for 2 qubit SWAP gate and it will be in the form of [a,b,c,d]")
y = SWAPgate((int(input('Enter the 1 st value   --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (int(input('Enter the 3rd value    --   '))),\
            (int(input('Enter the 4 th value   --   '))))

Enter  two values for 2 qubit SWAP gate and it will be in the form of [a,b,c,d]
Enter the 1 st value   --   1
Enter the 2nd value    --   1
Enter the 3rd value    --   0
Enter the 4 th value   --   1
[1 0 0 0] [1.] 
[0 0 1 0] [1.] 
[0 1 0 0] [0.] 
[0 0 0 1] [1.] 


[[1.]
 [0.]
 [1.]
 [1.]]


In [ ]:
#one qubit phase shift gate
import numpy as np, math
def onebit_PS(a,b,phi):
    matrix = np.array([[float(a)],[float(b)]])
    onebit_PS = np.array([[1,0],[0,np.around(np.cos(phi), decimals=5)+1j*np.around(np.sin(phi), decimals=5)]])
    result = np.matmul(onebit_PS,matrix)    
    for i in range(0, len(matrix)):
          print('{} {} '.format(onebit_PS[i],matrix[i]))
    print('\n')
    print(result)
  

#Calling onebit phase shift gate  
print("Enter  two values for 1 qubit phase shift gate and it will be in the form of [a,b,phase value]")
y = onebit_PS((int(input('Enter the 1 st value   --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (float(input('Enter the phase value  --   '))))


Enter  two values for 1 qubit phase shift gate and it will be in the form of [a,b,phase value]
Enter the 1 st value   --   0
Enter the 2nd value    --   1
Enter the phase value  --   3.14
[1.+0.j 0.+0.j] [0.] 
[ 0.+0.j      -1.+0.00159j] [1.] 


[[ 0.+0.j     ]
 [-1.+0.00159j]]


In [ ]:
#Two qubit phase shift gate
import numpy as np, math
def twobit_PS(a,b,c,d,phi):
    matrix = np.array([[float(a)],[float(b)],[float(c)],[float(d)]])
    twobit_PS = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,np.around(np.cos(phi), decimals=5)+1j*np.around(np.sin(phi), decimals=5)]]) 
    result = np.matmul(twobit_PS,matrix)
    for i in range(0, len(matrix)):
        print('{} {} '.format(twobit_PS[i],matrix[i]))
    print('\n')
    print(result)

print("Enter  two values for two qubit phase shift gate and it will be in the form of [a,b,c,d, phase value]")
y = twobit_PS((int(input('Enter the 1st value    --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (int(input('Enter the 3rd   value  --   '))),\
            (int(input('Enter the 4th value    --   '))),\
            (float(input('Enter the phase value  --   '))))

Enter  two values for two qubit phase shift gate and it will be in the form of [a,b,c,d, phase value]
Enter the 1st value    --   1
Enter the 2nd value    --   0
Enter the 3rd   value  --   1
Enter the 4th value    --   1
Enter the phase value  --   3.14
[1.+0.j 0.+0.j 0.+0.j 0.+0.j] [1.] 
[0.+0.j 1.+0.j 0.+0.j 0.+0.j] [0.] 
[0.+0.j 0.+0.j 1.+0.j 0.+0.j] [1.] 
[ 0.+0.j       0.+0.j       0.+0.j      -1.+0.00159j] [1.] 


[[ 1.+0.j     ]
 [ 0.+0.j     ]
 [ 1.+0.j     ]
 [-1.+0.00159j]]


In [ ]:
import numpy as np, math
def toffoli(a,b,c,d,e,f,g,h):
      matrix = np.array([[float(a)],[float(b)],[float(c)],[float(d)],[float(e)],[float(f)],[float(g)],[float(h)]]) 
      toffoli = np.array([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0]])
      result = np.matmul(toffoli,matrix)  
      for i in range(0, len(matrix)):
            print('{} {} '.format(toffoli[i],matrix[i]))
      print('\n')
      print(result)
print("Enter  two values for 3 bit ccnot or toffoli gate and it will be in the form of [a,b,c,d,e,f,g,h]")
y = toffoli((int(input('Enter the 1 st value   --   '))),\
            (int(input('Enter the 2nd value    --   '))), \
            (int(input('Enter the 3rd value    --   '))),\
            (int(input('Enter the 4th value    --   '))),\
            (int(input('Enter the 5th value    --   '))),\
            (int(input('Enter the 6th value    --   '))),\
            (int(input('Enter the 7th value    --   '))),\
            (int(input('Enter the 8th value    --   '))))

Enter  two values for 3 bit ccnot or toffoli gate and it will be in the form of [a,b,c,d,e,f,g,h]
Enter the 1 st value   --   0
Enter the 2nd value    --   0
Enter the 3rd value    --   0
Enter the 4th value    --   0
Enter the 5th value    --   0
Enter the 6th value    --   0
Enter the 7th value    --   1
Enter the 8th value    --   0
[1 0 0 0 0 0 0 0] [0.] 
[0 1 0 0 0 0 0 0] [0.] 
[0 0 1 0 0 0 0 0] [0.] 
[0 0 0 1 0 0 0 0] [0.] 
[0 0 0 0 1 0 0 0] [0.] 
[0 0 0 0 0 1 0 0] [0.] 
[0 0 0 0 0 0 0 1] [1.] 
[0 0 0 0 0 0 1 0] [0.] 


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]


In [ ]:
import numpy as np, math
def five_Hgate(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,bb,cc,dd,ee,ff):
      H = 1/math.sqrt(2)*np.array([[1,1],[1,-1]])
      matrix = np.array([[a],[b],[c],[d],[e],[f],[g],[h],[i],[j],[k],[l],[m], \
                         [n],[o],[p],[q],[r],[s],[t],[u],[v],[w],[x],[y],[z], \
                        [aa],[bb],[cc],[dd],[ee],[ff]]) 
      print(matrix)
      five_Hgate = np.kron(H,np.kron(H,np.kron(H,np.kron(H,H))))
      result = np.matmul(five_Hgate,matrix)
      print('\n','\n'"Find below output where five qubit Hadamard applied to above statp")
      print('\n',result)
print("Here standard base input is given as it is very big to take input below and it\
 is dynamic and we can change value any time" )

print("It will be in the form of Hadamard gate applied to basis state ")    


five_Hgate(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)


